[package]
name = "redo-rs"
version = "0.1.0"
authors = ["Ross Light <ross@zombiezen.com>"]
edition = "2018"

[dependencies]
common-path = "1.0.0"
failure = "0.1.6"
libc = "0.2.67"
libsqlite3-sys = "0.17.1"
nix = "0.17.0"
rusqlite = "0.21.0"
