name: Build
on: push
jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
