name: Build
on:
  push:
    branches:
      - '**'
jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest]
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Set up Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
    - name: Run tests
      run: minimal/do test
