name: Build
on: push
jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        cargo_args: [""]
        include:
          - os: macos-latest
            cargo_args: --features=debug-jobserver
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: ${{ matrix.cargo_args }}
